import { Router } from "express";
import { upload } from "../config/multer_config.js";
import { downloadDocument, saveSignature, uploadDocument,getMyDocuments, getDocumentStats } from "../controllers/document_controller.js";
import { verifyToken } from "../utils/token_manager.js";
const docRoutes = Router();
docRoutes.post("/upload/:userId",upload.single("pdf"),uploadDocument);
docRoutes.patch("/signature/:id",saveSignature);
docRoutes.get("/download/:id",downloadDocument);
docRoutes.get("/my-documents",getMyDocuments);
docRoutes.get("/documents_counts",getDocumentStats);
export default docRoutes;